### ISSUE TITLE
Missing cacert from window build (jdk8u172-b11)

### ISSUE THREAD

**Issue by nrousseau** [AdoptOpenJDK/openjdk8-releases#11]
Hello,

Actually the file cacert  for the windows build is empty, ie:

jdk8u172-b11/jre/lib/security/cacert

Everything is ok for mac / linux builds, but not windows.

Is it possible to get a new release build with the certificate file?

Thanks

**Comment by DanHeidinga** [comment]
FYI @jefrajames - tagging you in this item so you can track the status as we'll close the OpenJ9 issue

**Comment by donbourne** [comment]
I encountered this same issue last.  We were trying to do maven builds, as part of a lab for a conference.  Since maven was trying to connect to the maven repo it failed on the SSL handshake since the cacerts weren't present.  I had to copy the certs from a linux build to get the lab to work... so +1 for fixing this.

**Comment by planetf1** [comment]
Hit this same problem. Built fine on oracle 172. Switched to openjdk 171, still built fine. Then a few days later a colleague added a new dependency and wham! maven fell over as it couldn't pull an artifact. This is a breakage.

Note that ubuntu 18.04's openjdk build (not adopt) has similar issues - there I ended up copying the cacert file from an oraclejdk... (in both cases format was old style not java 9/10 for the keystore)

**Comment by sxa555** [comment]
>  Built fine on oracle 172. Switched to openjdk 171, still built fine. 
@planetf1 Can you clarify where "openjdk 171" came from that you're having an issue with please? The release builds at adoptopenjdk.net are 8u172 not 8u171.

**Comment by planetf1** [comment]
I said '71' as I assumed the 71 in the bad version string (another issue open on this) was a truncated 171, but perhaps not.

MacOS

13:52 $ java -version
openjdk version "1.8.0-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_05_19_02_01-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

**Comment by planetf1** [comment]
It's labelled jdk8u171-b11 when downloaded - yet it's unclear how to resolve that against a command I can run in the installed environment to show what is installed. there should be some match!

In full:
13:54 $ java -XshowSettings:properties
Property settings:
    awt.toolkit = sun.lwawt.macosx.LWCToolkit
    file.encoding = UTF-8
    file.encoding.pkg = sun.io
    file.separator = /
    gopherProxySet = false
    java.awt.graphicsenv = sun.awt.CGraphicsEnvironment
    java.awt.printerjob = sun.lwawt.macosx.CPrinterJob
    java.class.path = .
    java.class.version = 52.0
    java.endorsed.dirs = /Users/jonesn/java/jdk8u172-b11/jre/lib/endorsed
    java.ext.dirs = /Users/jonesn/Library/Java/Extensions
        /Users/jonesn/java/jdk8u172-b11/jre/lib/ext
        /Library/Java/Extensions
        /Network/Library/Java/Extensions
        /System/Library/Java/Extensions
        /usr/lib/java
    java.home = /Users/jonesn/java/jdk8u172-b11/jre
    java.io.tmpdir = /var/folders/fb/mzlmglkd11g00z2wgc4m15nw0000gn/T/
    java.library.path = /Users/jonesn/Library/Java/Extensions
        /Library/Java/Extensions
        /Network/Library/Java/Extensions
        /System/Library/Java/Extensions
        /usr/lib/java
        .
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 1.8.0-adoptopenjdk-jenkins_2018_05_19_02_01-b00
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0-adoptopenjdk
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Oracle Corporation
    java.vm.version = 25.71-b00
    line.separator = \n
    os.arch = x86_64
    os.name = Mac OS X
    os.version = 10.14
    path.separator = :
    sun.arch.data.model = 64
    sun.boot.class.path = /Users/jonesn/java/jdk8u172-b11/jre/lib/resources.jar
        /Users/jonesn/java/jdk8u172-b11/jre/lib/rt.jar
        /Users/jonesn/java/jdk8u172-b11/jre/lib/sunrsasign.jar
        /Users/jonesn/java/jdk8u172-b11/jre/lib/jsse.jar
        /Users/jonesn/java/jdk8u172-b11/jre/lib/jce.jar
        /Users/jonesn/java/jdk8u172-b11/jre/lib/charsets.jar
        /Users/jonesn/java/jdk8u172-b11/jre/lib/jfr.jar
        /Users/jonesn/java/jdk8u172-b11/jre/classes
    sun.boot.library.path = /Users/jonesn/java/jdk8u172-b11/jre/lib
    sun.cpu.endian = little
    sun.cpu.isalist =
    sun.io.unicode.encoding = UnicodeBig
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = UTF-8
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level = unknown
    user.country = GB
    user.dir = /Users/jonesn/Downloads
    user.home = /Users/jonesn
    user.language = en
    user.name = jonesn
    user.timezone =

**Comment by karianna** [comment]
This issue was moved to AdoptOpenJDK/openjdk-build#478
