### ISSUE TITLE
sun.* source code not included in src.zip

### ISSUE THREAD

**Issue by don-vip** [AdoptOpenJDK/openjdk8-releases#9]
I have downloaded this binary:
https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u144-b01/OpenJDK8_x64_Win_jdk8u144-b01.exe

Once installed, it appears `sun.*` source code is not included in `src.zip`.
As at least the class I'm interested in (`src/share/classes/sun/util/locale/provider/NumberFormatProviderImpl.java`) is licensed under GPLv2, coud you please include in src.zip all the source code we can find in OpenJDK repositories?

**Comment by gdams** [comment]
@neomatrix369 any ideas about this?

**Comment by neomatrix369** [comment]
@gdams No idea why this would be the case, we are archiving the image folder as it it produced by the build process , see [src.zip](https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_windows/ws/openjdk/build/windows-x86_64-normal-server-release/images/jdk8u162-b01/src.zip) in https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_windows/ws/openjdk/build/windows-x86_64-normal-server-release/images/jdk8u162-b01/.

**Comment by neomatrix369** [comment]
@don-vip Can you please point us to OpenJDK Windows builds (produced anywhere else) in which the src.zip does contain the file you are looking for?

**Comment by don-vip** [comment]
? There is not. I'm asking to include the missing files. If they were already included, I wouldn't have created the ticket :)

**Comment by neomatrix369** [comment]
@don-vip Thanks for clarifying.

It would mean changing the build script, have a look at http://jdk.java.net/java-se-ri/8 and then the http://download.java.net/openjdk/jdk8u40/ri/openjdk-8u40-src-b25-10_feb_2015.zip, which does not contain the file you are talking about either.

@gdams @karianna what do you think about the request? Our build script will fork away from the standard OpenJDK one if we implement this, is this desirable for the medium/long run?

**Comment by karianna** [comment]
@neomatrix369 Worth asking upstream OpenJDK folks why this isn't included (for jdk8u).   I can't see any reason *not* to include it if it's GPLv2 with Classpath and not a closed Sun/Oracle class.

**Comment by tellison** [comment]
FYI it has been true 'forever' that src.zip does not contain all the library source code.  That zip file is produced to assist development tools display relevant source code.  IMHO it should contain *less* source than it already does.

Now that we are all connected, better still we should simply include coordinates to the git repo sources that produced the build so that dev tools can reach on-line the entire code from which the binaries are produced if they so choose.

**Comment by karianna** [comment]
@tellison Good point, we could provide the link to the tag in Github in the download.

**Comment by karianna** [comment]
This issue was moved to AdoptOpenJDK/openjdk-build#476
